### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#1]
We should have a Notification system.

Notifications are:
Some of my friends posted something
Some of my firends liked/disliked something 
Someone liked my Post
Someone comment on my Post

Garbage Collection:
We should remove any notifications after 7 days

Maybe some special system notification have longer ttl.

**Comment by andreas83** [comment]
I like to evalutate the new notication api too:

http://www.heise.de/ix/meldung/Web-Notifications-W3C-verabschiedet-Benachrichtigungsspezifikation-2854088.html

**Comment by chilimatic** [comment]
find ich gut, ist das schon implementier in die apis ? ansonsten ist es nett aber nicht verwendbar so wie ecma6 :/

**Comment by andreas83** [comment]
waren auch meine überlegungen. 
wollte es mir mal anschauen, ob es überhaupt den Zweck erfüllt und natürlich auch 
ob es von den Browsern in absehbarer Zeit unterstützt wird.

**Comment by chilimatic** [comment]
http://caniuse.com/#search=notification laut dem schaut's mittelmässig aus :/

**Comment by andreas83** [comment]
Aber irgendwie wäre es von der Funktionalität das richtige... 
Wollte es ja ursprünglich in die firefox und chrome extension integrieren, letzteres funktioniert übrigends jetzt auch mit der neuen API.
Ich werd mal recherchieren ob und wann IE die notification api implementiert, mit Chrome, Firefox und Safari sind ja schonmal die wichtigsten da.

**Comment by chilimatic** [comment]
wenn dir das reicht, aber du wolltest es kommerziell haben und da ist der IE noch immer sehr wichtig :D ich persönlich vernachlässige ihn ja mit viel freude :D

**Comment by andreas83** [comment]
Die nächste Frage die ich mir stelle, sockets mit php ja nein alternativen -

**Comment by chilimatic** [comment]
php: https://github.com/reactphp/react 
node: socket.io
go: https://github.com/googollee/go-socket.io
python: kA ist eine lib _gg_

das sind mal die sprachen und pakete die ich kenn / kann ansonsten fällt mir grad nix ein.

**Comment by andreas83** [comment]
Okay basic notifications via websockets now working! 
But there is a drawback, right now the getNotifications method only called once the user visits the page.

# TODO

Notify user on new event (i.e. comment) without reasking the server over and over again.

## Steps

1.) Notifiy websocket server (app/server) about new event (i.e. comment )
2.) Notifiy $user about this event ($socket->send($user, $msg)) 

i really get stuck on the first step. 
One soloution could be to have a websocket client written in php which notify the server about the new events. Another soloution could be to dispatch new events like client event->socket server-> api -> db 

@chilimatic I would appreaciate hearing your thoughts on this!

**Comment by chilimatic** [comment]
hmm ich hab mal bissi am code kommentiert generell find ich ihn okay, ich muss allerdings vortrag vorbereiten sonst würd ich bissi rum experimentieren und dir feedback geben. wenn du bis nächste woche warten kannst, da sollt ich wieder wirklich zeit haben mir das anzusehen, ich hab's nur mal überflogen.

**Comment by andreas83** [comment]
I just fixed my two main issues: 820960d094e3609dcfa7a93a1a6599d210a11ebc
1.) Notifiy websocket server (app/server) about new event (i.e. comment, mentions )
2.) Notifiy $user about this event ($socket->send($user, $msg))

This works pretty well so far, but some other components could benefit from
websocket server too

i.e.
Comments (for updates), Notification about new posts, Chat. 

I will address this issues in a next feature release.
