### ISSUE TITLE
remove old other project code remnants

### ISSUE THREAD

**Issue by chilimatic** [andreas83/SocialNetwork#10]
we need to clean up the old code so we don't have any other pre-projects remnants in there

**Comment by chilimatic** [comment]
you know best what needs to be removed :)

**Comment by andreas83** [comment]
hab alles soweit gelöscht bis auch zwei Sachen:
1.) FirePHP 
Kann man evtl. nochmal gebrauchen

2.) CSS vom Syntaxhighlighter 
Falls wir nochmal das Theme wechseln

**Comment by chilimatic** [comment]
Cool :D wollts nur mal draussen haben :D
