### ISSUE TITLE
should we support mp4 too?

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#12]
@besn @chilimatic @neuron303 

some apple boys not able to play webm, so we could transcode every video to mp4 too. 
is it worth the effort/disc space, your opinion please?!

**Comment by neuron303** [comment]
yes, but i would only see it as low priority.. i would rather file a bug/feature request with apple to support webm ;)

**Comment by andreas83** [comment]
@neuron303 :+1:
