### ISSUE TITLE
split components from react.jsx into smaller chunks

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#15]
Right now to much stuff happens in one file (react.jsx).
We should split the components into smaller chunks, i.e.
## Rendering

Content Box with following types:
- Video
- Websites
- Sourcecode
- Images 
- File uploads
## Functions

1.) Sharing Box
2.) Comment Box
3.) Like/Dislike Box
4.) Scroll Event

**Comment by chilimatic** [comment]
That's no bug :D btw since it's moving toward parallel development i think i drop the angular branch.

**Comment by andreas83** [comment]
imho bad coding practice should be treated like other serious programming errors aka bugs, that s the reason why i label this as a bug.  
@angular, i still believe that single page app should be our ultimate goal, angular is properly the right framework for it, but also meteor or sail,js could fit our need too..  
so lets invest some more time to find or write the "ultimative" framework :)

iam slightly curious about the experience you made with angular, the good, the bad the ugly stuff ?
tell me more about your experience you made, of cause we can have a quick phone, skype call too. 

best
andrea

**Comment by chilimatic** [comment]
well in generall I'm not really sure if meteor or sail.js are a good choice unless we switch the codebase to javascript, since both are node. 

there is no ultimative framework every fw has it's pitfalls. for me the decision to stick to one is more important than the rest. just pick one make a decision and stick to it.

**Comment by andreas83** [comment]
I started refactoring the react.jsx and splitted its components into smaller files Author.jsx, Comments.jsx, Likes.jsx, Stream.jsx and also renamed StreamBox to InitStream.

67f5eee9ee651f3be2bf672fd0e701d755cc4471

I guess some future work on refactoring needs to be done, but this ticket can be closed for now.
