### ISSUE TITLE
Hook / Slot System

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#20]
We properly need a hook / slot system. 
This can be useful for extension programming, think about do something before/after a method is called. 

Something like
$obj->addHook((obj)$user, "save", (obj)$plugin, "sendmail"); 

This triggers the method "sendmail" from Object $plugin, 
while the save method from $user object is called.

Open Questions:
1. How to handle parameters. 
2. Option for pre / after hook

@besn @chilimatic @neuron303  your input is always highly appreciated!

**Comment by chilimatic** [comment]
hmm es würd sich ein stack / queue system für das exekutionshandling anbieten. Es stacked events in 3 verschiedenen arrays (index basierende hashmap) wobei ich auf der index position eine SPLObjectstorage einfügen würde als "stack" da die \SPLObjectstorage automatisch nur objekte 1 mal drin zulässt. kann man allerdings auch mit einer doublelinkedlist oder mit dem klassischem array lösen.

``` php
if (isset($this->preEvents[$currentCall])) {
   $this->executeStack($preEvents[$currentCall]);
}

$this->executeSack($currentCall);

if (isset($this->postEvents[$currentCall])) {
   $this->executeStack($preEvents[$currentCall]);
}
```

man könnte allerdings auch einen Ansatz von funktionalen Sprachen verfolgen und den exekutionsablauf in listen aufteilen und diesen dann vor oder nach dem gewünschten aufruf einen anderen aufruf auf die liste oder subliste pushen. 

gibt meiner ansicht nach viele Möglichkeiten. du musst halt das "state" problem bedenken wenn du nicht immutable arbeites. Ich würde jedes objekt mit "clone $obj" übergeben, das kann bei unwissen zu Speicher-Problemen führen. Stellt aber sicher das eine post action die nächste nicht zerschießt weil sie das objekt manipuliert. 

du könntest dir allerdings auch einfach folgende runterladen
http://symfony.com/doc/current/components/event_dispatcher/introduction.html
https://pear.php.net/manual/en/package.event.event-dispatcher.example.php [warscheinlich nicht php7 kompatibel -> neue C headers etc]
oder dir http://www.chrisbrand.co.za/2013/06/22/design-pattern-event-dispatcher/ das mal durchlesen kA ich würd sagen für deine zwecke wäre warscheinlich 
https://github.com/peridot-php/event-emitter das eine idee :D 

das wären mal meine gedanken
