### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by Phumix** [andreas83/SocialNetwork#22]
Getting error 500 on http://www.dasmerkendienie.com/hash/test and when I try to install it on my own server. What could be wrong?

**Comment by chilimatic** [comment]
there is no test hash and the datacontroller tries to perform an operation on a "non object" which causes a fatal error if you're not using php7. That's just and educated guess but open the app/controller/DataController.php on line 257 and add "if ($res)" around             

```
        $res[0]->pop+=1;
        $res[0]->save();
        $this->assign("show_share", false);
        $this->assign("hash", $request['hash']);
        $this->assign("title", "Pictures of ".$request['hash'] );
```

please let me know if the guess was right ;) i havent installed it atm.

**Comment by andreas83** [comment]
issue should be fixed now, @chilimatic was right, we try to count the popularity of each hashtags, but 
at this point the hashtag #test did not exist. 

please test latest revision and let me know if the issue can be closed.

**Comment by chilimatic** [comment]
cool thx for the info:)
