### ISSUE TITLE
Report post & basic admin panel

### ISSUE THREAD

**Issue by Phumix** [andreas83/SocialNetwork#23]
Might be useful to add a basic function that allows users to report posts, and then have some sort of a admin panel where you can review these reports and either delete the post or keep it.

**Comment by andreas83** [comment]
is already planed and will be added to our next release cycle.

**Comment by andreas83** [comment]
We have now a basic admin panel. 
At least you can create, update, delete various models like User, Content, Comments etc. 
Next challenge will be to have other input fields than text and a way to 
configure special behavior like (password=>hash, date=>calendar) 
but this will be handled in #26 
I will leave this ticket open until the other request (report posts) is implemented.

**Comment by andreas83** [comment]
Report function added!
