### ISSUE TITLE
add @todo tags

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#24]
we need a overview which part of the application needs to be refactored.
i already added @todo tags with my thoughts, please share your idea with me too.
the goal is to improve code readability, so it will be much easier for other to contribute, to maintain, extend and so on. There are plenty of other [code smells](https://en.wikipedia.org/wiki/Code_smell), please help me to reduce them.

**Comment by andreas83** [comment]
@chilimatic @besn some input about code readability and improvements would be very helpful!  
you can comment here or directly inside sourcecode via @todo tags.
 :heart_eyes:  your thoughts are highly appreciated!

**Comment by andreas83** [comment]
splitted quite a lot function into smaller chunks:
9c4c50890f3a13612c6ee433a9717145b3e329f7

**Comment by andreas83** [comment]
Still searching for more idea to improve code quality and readability. 
@chilimatic idea about a output dispatcher will be implemented pretty soon.
please let me know if you like to see some other improvements too.

**Comment by chilimatic** [comment]
i believe I will join @coding within the next 3 Weeks for at least 3-4 hours a week (as you know I have my own pet projects I want to attend as well) :)

**Comment by andreas83** [comment]
i started to remove quite a lot of external dependencies and moved them to composer
altoroute, scssphp and also frontend libs like jquery, bootstrap and highlightjs 
are now handled by composer. 

right now you can clone the project and load dependecies by composer install 
but if you try via composer require movingbytes/social-network you will get an error
like 
`Could not find package movingbytes/social-network at any version for your minimum-stability (stable).`

And if you try to download it via: composer require movingbytes/social-network "dev-andrea" 
everything is installed to /vendor, which is bad because my app requires the vendor in /

any help is highly appreciated!

**Comment by andreas83** [comment]
Next i like to focus on JavaScript refactoring. 

Some Goals are:
- take advantage of webpack or/and browserify or/and bower 
- port stuff from main.js to react 
- i also like to reuse the new post component for editing stuff (right now its a complete separate functionality)

@chilimatic @besn @neuron303  and all others, your input is highly appreciated too !

**Comment by andreas83** [comment]
textarea aka share box with preview is now a react component. 
hopefully there is a way to reuse this component for editing posts.
