### ISSUE TITLE
admin panel aka automated generic backend

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#26]
We need an admin panel, with at least minimum generic functions like create, read, update, delete. 
I do not plan to create a separate controller, template for each model, instead i would love
to generate the admin panel from meta data. 
in example we could use doc code inside the model to describe the data other frameworks use config array or yaml
## What we need to generate an admin panel
1. Authentication for privileged users
   _Done_
2. We need to know which model should be editable
   Can be done via doc code or another declarative way. Other idea highly welcome too!
3. We need to define which properties are visible and editable also validation will be an issue. 

iam still thinking about a nice way how to render specific properties (like datetime picker, wyswyg editor or upload fields)

**Comment by andreas83** [comment]
Some more toughs:
we need a way to configure which properties of each model are:

1.) searchable
2.) editable
3.) visible at all 

Also pre/after hooks are necessary.

**Comment by sabanb** [comment]
Please help me how to login to admin admin panel

**Comment by andreas83** [comment]
I think we will move from automatic generated backend to static one, since this will give us more flexibility.
