### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#27]
Hello , how to install this script in my site?

**Comment by andreas83** [comment]
We will write a documentation very soon, for now i hope these 3 steps will guide you through...

# Instalation

## Download the Sourcecode

Via GIT: 
git clone https://github.com/andreas83/SocialNetwork.git

Via Download:
https://github.com/andreas83/SocialNetwork/archive/andrea.zip

## Configuration 

you can adjust the db credentials in app/config/main.cfg 
```
db_name="dmdn"
db_user="root"
db_pass="nv8xy0815d"
```
You will find the database.sql file in repro

Also you should adopt following configuration parameter
```
address="http://www.yourdomain.com"
dir="/home/lissi/tmp/dmdn/trunk";
```

For security reasons please don`t forget to change the salat to some other random string
```
salat="KJMnmnNUU&/§N(JH/h80h87fnunu43h8u7"
```

If you run Apache, you need also activate mod_rewirte 

```
a2enmod rewrite
```

## Sample nginx configuration

```
server {
  listen 217.11.57.227:80;
  listen [2a00:1828:2000:148::3]:80;

  server_name .dasmerkendienie.com;

  access_log /var/log/nginx/www.dasmerkendienie.com.access.log;
  error_log /var/log/nginx/www.dasmerkendienie.com.error.log info;

  root /home/dasmerkendienie/www/dasmerkendienie.com;
  index index.php;

  location ^~ /(css|img|js|upload|bootstrap) {
    # enable CORS (http://enable-cors.org/server_nginx.html)
    if ($http_origin ~ (https?://.*\.dasmerkendienie\.com(:[0-9]+)?)) {
      add_header "Access-Control-Allow-Origin" $http_origin;
    }
    root /home/dasmerkendienie/www/dasmerkendienie.com;
    expires 1d;
  }
  location /public/upload {
    deny all;
  }
  location /app/config {
    deny all;
  }
  location / {
    rewrite ^/public/css/scss.php/(.*)$ /public/css/scss.php?p=$1 last;
    try_files $uri /index.php?$args;

    location ~ .php$ {
      try_files $uri $uri/ =404;
      fastcgi_index index.php;
      fastcgi_read_timeout 1800s;
      fastcgi_send_timeout 1800s;
      fastcgi_pass phpcgi;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    # deny access to apache .htaccess files
    location ~ /\. {
      deny all;
    }
  }
}
```


Hope this helps

**Comment by ulamnet** [comment]
Thanks for this helpin but my site like this ; 
![likethis](https://cloud.githubusercontent.com/assets/583003/12417327/fb0c35f4-beaf-11e5-816a-5ef88170e296.PNG)

**Comment by ulamnet** [comment]
and this error in phpmyadmin . when ı install database.sql
![sqlerror](https://cloud.githubusercontent.com/assets/583003/12417374/5e3cb856-beb0-11e5-92fa-e413244101a8.PNG)

**Comment by andreas83** [comment]
7341684409eed2ac1e87c3cd904a71fb6a6df243 database.sql should work now

**Comment by ulamnet** [comment]
still my web page some error . here ; http://gifa.ga/test/

**Comment by andreas83** [comment]
I forgot, following directory must be writeable by webserver: public/css/scss/
on some webserver this can be done by:
```sudo chown www-data:www-data public/css/scss/```

**Comment by andreas83** [comment]
i never tried to run it on a sub directory, you properly need to add following line in header.php 

```<base href="http://gifa.ga/test/" />```

**Comment by ulamnet** [comment]
okay now working in www.gifme.ga but when ı share youtube videos not showing . and when photo sharing getting this error :  


Warning: move_uploaded_file(/home/lissi/tmp/dmdn/trunk/public/upload/569e555ca25733.48503242_gif1.PNG): failed to open stream: No such file or directory in /home/gifme/public_html/app/controller/DataController.php on line 279

Warning: move_uploaded_file(): Unable to move '/tmp/phpMmOwLc' to '/home/lissi/tmp/dmdn/trunk/public/upload/569e555ca25733.48503242_gif1.PNG' in /home/gifme/public_html/app/controller/DataController.php on line 279

Warning: Creating default object from empty value in /home/gifme/public_html/app/controller/DataController.php on line 281

Warning: mime_content_type(/home/lissi/tmp/dmdn/trunk/public/upload/569e555ca25733.48503242_gif1.PNG): failed to open stream: No such file or directory in /home/gifme/public_html/app/controller/DataController.php on line 283

Warning: Creating default object from empty value in /home/gifme/public_html/app/controller/DataController.php on line 285

Warning: Cannot modify header information - headers already sent by (output started at /home/gifme/public_html/app/controller/DataController.php:279) in /home/gifme/public_html/app/lib/BaseController.php on line 75

**Comment by andreas83** [comment]
the reason for the upload error is properly this line from app/config/main.cfg
dir="/home/lissi/tmp/dmdn/trunk";

@youtube issue, looks like there is more than just the youtube issue. 
because text is not displayed at all..  
can you confirm that its saved inside Content table ?

**Comment by ulamnet** [comment]
yes save , but nothing changes ... How to fix ?

**Comment by andreas83** [comment]
the question was, is you Content table empty or not?

**Comment by ulamnet** [comment]
not .

**Comment by andreas83** [comment]
whats inside your error logs ?

**Comment by Phumix** [comment]
What would case this error "Disconected from notification server"? It's displayed to right under the "Fork me on Github" text. I see he has that error.

**Comment by chilimatic** [comment]
I guess you have to run this 
https://github.com/andreas83/SocialNetwork/blob/andrea/app/server/runnotificationServer.php 

"php <path_to_your_checkout>/app/server/runnotificationServer.php &" in the console :)
this should create a "notification-service" which listenes on port 9000.

But I don't have it installed, I just read the code :)

**Comment by Phumix** [comment]
I just tried this, still getting same error.

**Comment by chilimatic** [comment]
what does "netstat -lnp | grep 9000" return ? 
if there is no open 9000 port or another service is using port 9000 you should try to use
"php /app/server/runnotificationServer.php" so you can see if there is a php error happening :)

**Comment by Phumix** [comment]
netstat -lnp | grep 9000
    tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      5486/php


Port 9000 is open

**Comment by chilimatic** [comment]
hmmm well now I have to guess, you could check the JS code and intercept the notification API with a console.log() but tbh, I would have to install it. If you can wait till tomorrow I will try to reproduce your error and finde a solution.

In the meantime you could give me your browser + OS + Version so I can create a propper testcase :)

**Comment by Phumix** [comment]
Running Windows 10 and I've tested it in Chrome 47.0.2526.111. Also tested with Mozilla Firefox 43.0.4.

**Comment by chilimatic** [comment]
@Phumix cool, thx ! :) In this case it's not likely to be a client issue since both implement the notification API. But still I have to test it myself since I'm just guessing here :)

@andreas83 I will create a phing script which should create the correct permissions and structures

**Comment by andreas83** [comment]
@chilimatic thx !! 

the trouble with the notification service is thise line:
```var host = "ws://127.0.0.1:9000/notification"; // SET THIS TO YOUR SERVER```

this must be set in public/js/main.js  we should move this to app/config/main.cfg  

still i like the idea of the phing script!!

**Comment by Phumix** [comment]
The new update has errors, notification thing says this now:

    SyntaxError: Failed to construct 'WebSocket': The URL '' is invalid.

**Comment by andreas83** [comment]
whats inside your main.cfg ? 
```
notification_server="ws://127.0.0.1:9000/notification";
```

**Comment by Phumix** [comment]
@andreas83 
This part? I didn't touch that, it looked fine

    # Please point this to your Notification server
    notification_server="ws://127.0.0.1:9000/notification";

**Comment by andreas83** [comment]
@Phumix 
i assume the error is from js ? 
in theory the variable "notification_server" from main.cfg should be rendered in 
app/template/footer.php and than is used by 
public/js/main.js 
```socket = new WebSocket(notification_server);```

please make sure the variable is declared in main.cfg and rendered in footer like this:
```
<script>var notification_server="ws://127.0.0.1:9000/notification";  </script>
```

**Comment by Phumix** [comment]
@andreas83 I've solved the syntax error. However I am still getting the "Disconected from notification server" error. I've ran "php app/server/runnotificationServer.php" and the port shows as online when I check with example http://www.yougetsignal.com/tools/open-ports/. So basically, how I see it. It's unable to make a connection between the script and the open port.

**Comment by andreas83** [comment]
is maybe a stupid question, but did you try to change the notification servers ip to the public ip ?

**Comment by Phumix** [comment]
@andreas83 Of course, and there is no stupid questions.

**Comment by andreas83** [comment]
Can you etablish a connection to your websocket server via this tool:
http://www.websocket.org/echo.html

**Comment by Phumix** [comment]
@andreas83 It says connected when I do so.

**Comment by andreas83** [comment]
@Phumix  

so the error must be eigther in public/js/main.js where we connect to the socket server
`            socket = new WebSocket(notification_server);
`

or in app/template/footer.php where we set the notification_url from config (app/config/main.cfg)
`
echo "<script>var notification_server=\"".Config::get("notification_server")."\";  </script>";
`

**Comment by andreas83** [comment]
i think the main issue "how to install"  is resolved.
if the  issue with the notification server persist, please open a dedicated issue.
