### ISSUE TITLE
 No such file or directory in

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#34]
Hello , ı some get this error ;

Warning: include_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/kimmoda/public_html/init.php on line 6

Warning: include_once(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/kimmoda/public_html/init.php on line 6

Fatal error: Class 'AltoRouter' not found in /home/kimmoda/public_html/routing.php on line 3

**Comment by chilimatic** [comment]
You need to run composer. :)

**Comment by ulamnet** [comment]
sorry, my bad english. I dont understand.Please clear tell me ?

**Comment by chilimatic** [comment]
Ahh i see. 
Composer is an dependencymanagemt programm. You can download it at :http://getcomposer.org

I asume you wont create a symlink to /usr/bin/ but use it as a normal phar

You need to copy it into the installation folder of the website (NOT the web folder) than you need to make sure it has the executionflag chmod +x composer.phar. 

Next you just have to type php composer.phar install and it will download all the  needed packages :)

I hope thats better. I can write it in german as well but those are the only two languages i do speak :)

**Comment by andreas83** [comment]
i learn spanish, so if it helps, i could try to translate :)

**Comment by ulamnet** [comment]
thanks :) but ı speak turkish :)

**Comment by andreas83** [comment]
maybe this helps:
http://kulekci.net/php-the-right-way/#bagimlilik_dependency_yonetimi

**Comment by andreas83** [comment]
1.) install composer 
https://getcomposer.org/download/
2.) now install the missing dependencies via comand line:
`cd SocialNetwork;
composer install`

hope it helps, if you need futher support, just let me know.

**Comment by ulamnet** [comment]
I install composer sucessfully , but when work comand line something wrong.

**Comment by ulamnet** [comment]
ah okay, now working fine , thanks.
