### ISSUE TITLE
mentions @me and #hashtag autocompleter

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#35]
would be cool, if someone like to help me implementing a fb and twitter like mention box. 

useful resources: 
http://yuku-t.com/jquery-textcomplete/

**Comment by Phumix** [comment]
then we should implement this #1  as well, so the mentions comes up as notifications

**Comment by andreas83** [comment]
task done, also with notifications for people who get mentions @Phumix  @besn
