### ISSUE TITLE
Upload any file

### ISSUE THREAD

**Issue by Phumix** [andreas83/SocialNetwork#38]
I figured it's possible to upload any file as avatar/upload any file on posting. This means .html files can be uploaded and used. I tried to upload a PHP file to test if that worked but it didn't. Which is good. 

Anyways, restrict avatar uploads to only jpg, jpeg, png and bmp extension?

**Comment by andreas83** [comment]
thanks for your valuable feedback !

**Comment by andreas83** [comment]
fixed, please test
