### ISSUE TITLE
Order data by score

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#39]
I like to order the Post by Score (on a daily basis)

What i did so far, 
`select Content.id,  count(Score.id) as score from Content left join Score on Content.id=Score.content_id  group by Content.id order by DATE(from_unixtime(Content.date)), score asc`

This works pretty well, until i fetch some more data via limit offset...  

**Database Table Score**

```
mysql> desc Score;
+------------+-------------------+------+-----+---------+----------------+
| Field      | Type              | Null | Key | Default | Extra          |
+------------+-------------------+------+-----+---------+----------------+
| id         | int(10) unsigned  | NO   | PRI | NULL    | auto_increment |
| user_id    | int(10) unsigned  | NO   | MUL | NULL    |                |
| content_id | int(10) unsigned  | NO   |     | NULL    |                |
| type       | enum('add','sub') | NO   |     | NULL    |                |
| date       | int(10) unsigned  | NO   |     | NULL    |                |
+------------+-------------------+------+-----+---------+----------------+
5 rows in set (0,00 sec)
```

Maybe it makes sense to pre count the score in Content, so the left join will not nessesary while fetching new data. But this would just improve read performance. 

Another problem is, right now we fetch x posts from given id!
In example 10 posts from id 12040, this will return us 12039, 12038 ...  and so on. 
this works pretty well, because our data is ordered by id. 

with the new feature, the result is not ordered by id anymore. 
so the result could look like 12037, 12040, 12039 .....  

Right now we would use the last id, and fetch 10 more posts while scrolling. 
In this scenario, we would fetch several post twice. 
But if we fetch, 10 post from the lowest id (i.e. 12037) we may miss some post too. 

@neuron303 @chilimatic @besn  any hints ?

**Comment by chilimatic** [comment]
I think about a view that stores the score and btree indexes in that view for faster ordering. So the normal post inserts wont be affected. 

this is just top of my head I would need to spend time looking at the model an experiment with it.

**Comment by andreas83** [comment]
my final query looks like this
`SELECT *, count(Score.id) as score, Content.id AS id, User.id as user_id FROM Content INNER JOIN User on Content.user_id=User.id LEFT JOIN Score on Content.id=Score.content_id WHERE Content.id < 1000000000 group by Content.id order by DATE(from_unixtime(Content.date)) desc, score desc, Content.id desc`

I will upload the soloution to demo and make some performance benchmark tests.

**Comment by chilimatic** [comment]
coool :) i hope I got time tomorrow and have a look at it :) I was working till 5 minutes ago :)

**Comment by andreas83** [comment]
i'm curious to see some performance benchmarks view vs left join, vs own column...

**Comment by andreas83** [comment]
mhm some user reported this feature as a bug, because the were confused by the new ordering ....

e9142c895c16f1e19eb98904df60afeeb226b0f6

**Comment by andreas83** [comment]
Ordering by score can be interesting for sure, but maybe it makes more sense to order 
by activity/popularity. comments, likes, views etc.
So we may end up with a tracking system, which can be useful for understanding the user habits. 

:heart: how i make every task overcomplex and nearly impossible to solve.

**Comment by chilimatic** [comment]
I'm not sure if it's over complex. 

I think this article helps to understand that the problem is only really complex using the classic SQL RDBMs .
http://www.cray.com/blog/graph-databases-101/
he really nails the usecase for graph databases and as you will read networks are a specific target. 

Then read this :) as an easy kickstarter for a timeline idea :)
http://www.sitepoint.com/efficient-user-timelines-php-application-neo4j/

If you don't like it at least I hope you had a good read meanwhile :)
