### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#40]
Hello , how to login backend ? I know url/backend/ but what is mail and password?

Thanks.

**Comment by andreas83** [comment]
mhm good question! 
Right now we do not have any default admin user, 
So you can have to set the isAdmin flag in mysql table User to your registered existing user. 
After that you can just can login via url/backend. 

Please keep in mind that the admin/backend is a work in progress.

**Comment by ulamnet** [comment]
okay ,  I understand , thanks :)
