### ISSUE TITLE
timeline

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#43]
Hello , why timeline like this ? ı share just now video but my sharing ı see The bottom but ı see 7 minutes sharing ago top. Sorry my bad english again :)

![adsiz](https://cloud.githubusercontent.com/assets/583003/13785782/838bf9ba-eadd-11e5-8f76-b2e179fac428.png)

**Comment by ulamnet** [comment]
try my site : http://callme.ga/

**Comment by andreas83** [comment]
Because of #39 
We sort post by score & date, so if you dont like it, you could remove following line in 
app/model/Content.php 

```
if($show!="1")
        {
            $orderby="order by  DATE(from_unixtime(Content.date)) desc, score desc, Content.id desc"; 
            $leftJoin=" LEFT JOIN Score on Content.id=Score.content_id ";
            $score ="count(Score.id) as score,";
        }
```

**Comment by ulamnet** [comment]
not work for me.s

**Comment by andreas83** [comment]
mhm since this "feature" is highly confusing, i will remove it soon ...

**Comment by andreas83** [comment]
"fixed"
