### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#47]
Hello , again me :)

but why register page like this?

http://siwip.com/user/register/

![siwip2](https://cloud.githubusercontent.com/assets/583003/13903570/93374c3e-ee89-11e5-9a65-2f9f2c435e89.PNG)

**Comment by ulamnet** [comment]
are you there @andreas83

**Comment by andreas83** [comment]
@ulamnet 

1.) please run composer update
2.) check your configuration, try to disable google and facebook auth for testing

; Facebook Auth
facebook_auth=true;
facebook_app_id="";
facebook_app_secret="";

; Google Auth
google_auth=true;
google_app_id="";
google_app_secret="";

**Comment by ulamnet** [comment]
Ok , now working but without facebook and google login.

**Comment by andreas83** [comment]
You need an app id and secret to use this feature:

Get APP ID and Secret from Facebook here:
https://developers.facebook.com

And Google here:
https://cloud.google.com/
