### ISSUE TITLE
Two accounts on same e-mail

### ISSUE THREAD

**Issue by Phumix** [andreas83/SocialNetwork#48]
It's possible to have two or more accounts on same e-mail with different passwords. Check my accounts "merfin" and "martin. I can't really remember how I did it, but I think I just created them on same e-mail.

**Comment by andreas83** [comment]
Quite interesting, this should not be possible!
Please let me remove your test accounts: MartinTest && merfin and let me 
know if you can reproduce this error !?

**Comment by Phumix** [comment]
Yes, of course. I had another one but I forgot the username.

**Comment by andreas83** [comment]
is this still an issue ?

**Comment by Phumix** [comment]
Yes, it is. I was able to create another account on same e-mail. Check account "mertin". Has same e-mail.

**Comment by andreas83** [comment]
should be fixed for now.
