### ISSUE TITLE
Create Random-Slideshow in the home/jumbotron

### ISSUE THREAD

**Issue by chilimatic** [andreas83/SocialNetwork#5]
As a nice "splash/landingpage" feature we should display a random !!SFW!! slideshow on the start page

**Comment by andreas83** [comment]
cool idea!
should we display the latest newest stuff or anything from a specific hastag #landingpage
or completly random?

**Comment by chilimatic** [comment]
:D actually I don't mind :) I would go for this order: "highest, latest" and since it's the landing page i would exclude NSFW content. So even if you're logged in or not does not matter you can always open it anywhere :) 

and to keep things simple at the beginning it should only be a public stream so we can implement it first and add features to it in the long run. (add personal filters to jumbotron stream)

**Comment by andreas83** [comment]
now we have random cat images there as example implementation. 
(of cause we can use other hashtags to, also the amount and order can be configred by getNext() metod)
