### ISSUE TITLE
Vagrant container

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#51]
I think its a good idea to have a docker container.

**Comment by chilimatic** [comment]
for which component/s ?

**Comment by andreas83** [comment]
thought about everything, let us have a quick chat about the pro/con

**Comment by andreas83** [comment]
i try to redefine the requirements: 

story style: 
We need a way to ship the SocialNetwork as Package with all required dependencies (database, webserver,  notification server etc). 
Customers should be able to extend and adopt the existing Software, while at the same time we should be able to distribute major updates...
Also another aspect is scalability, which requires separation of each micro service (api, notification server etc). Since scalability is not that important right now, i like to focus on package distribution and dependency management.

**Comment by andreas83** [comment]
I think for the first part, virtualbox will suite our needs and works pretty well as out of the box solution. 
For dependency management and scalability i will open a separate ticket

**Comment by chilimatic** [comment]
I hope you mean vagrant, not just vbox the provisioning should be like docker, versioned :)
Personally I think it's okay to skip docker atm but I wouldn't just use vbox without a provisioning system. 

And more importantly what's the difference between the port/directory mapping problems in virtualbox and docker ? A Virtual-Machine like a normal Machine will still have the same problem Stack. 

But lets wait and see if it crashes, I can see a lot of problems that will arise but you need to get there first :)

**Comment by andreas83** [comment]
Yes i mean vagrant, i will try to create a image now...

**Comment by andreas83** [comment]
okay i failed miserably. 
is there someone with more experience with vagrant & puppet?

@besn @chilimatic  ?! anyone ?

**Comment by chilimatic** [comment]
Vagrant kann ich, puppet hab ich noch ned so viel rumgespielt ich hab nur erfahrung mit stateless agents wie fabric. Also ausser aus user-sicht ich weiß wie die files aussehen :D und wie das system funktioniert :D 

@besn du kennst und kannst beides :)

**Comment by andreas83** [comment]
@besn told me he knows puppet, but cant help us with vagrant ... 
so guess, nobody is able to create a proper vagrant container right now.
i will close this ticket for now...

**Comment by chilimatic** [comment]
i can create a proper vagrant container ;) I just don't see the point in vagrant for anything else than development. Basically you run in the port problems so docker does make much more sense esp the overhead :)

but anyway _gg_ close it :D
