### ISSUE TITLE
Page system, User details

### ISSUE THREAD

**Issue by ghost** [andreas83/SocialNetwork#53]
Maybe system for creating fan pages would be great, also if user profile could be filled with user details, such as location, bio, work, etc...

**Comment by andreas83** [comment]
thanks for your feedback!
i like the idea of having a real profile page!
how could a fan page look like?

**Comment by ghost** [comment]
Fan page could be similar to Facebook's one. Basic information about page (website, phone, etc..) and timeline of posts made by fan page (its admins). In future there could be a lot more to do - fan page insights, promote post and so on.
