### ISSUE TITLE
create integration tests 

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#57]
at the beginning integration tests for the API would be cool

content
- [ ] post content 
- [ ] get content
- [ ] put aka update content
- [ ] delete content

comment
- [ ] post comment 
- [ ] get comment

**Comment by andreas83** [comment]
after we added namespaces and autoloading it turns out, that we can not test the whole application manually anymore. So next release will focus only on Unit Tests! 
Main Goal is just testcases for the API, since they isolated by design and cover the important functionality but afterwards testcases for the rest is mandatory.

**Comment by andreas83** [comment]
Added my first unit test (iam so proud of me)
42067b04413303b770d42bdfd05cd4ee5136841f

Now i need a way to have some test data, while testing.

One idea is, storing a testdatabase.sql file and using it for all api request. 
downside: someone have to maintain this file...  

other idea:
http://dbv.vizuina.com/
https://phinx.org/

@chilimatic any recommendations ?

**Comment by chilimatic** [comment]
I use phinx :) but it has some issues if you wanna use an auto_increment on a field that's not called "id"
