### ISSUE TITLE
Class 'transformer\TransformerFactory' not found

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#59]
While trying to share some youtube video ie.
https://youtu.be/yfCt35RTR-U

i got following error:
Fatal error: Class 'transformer\TransformerFactory' not found in /home/lissi/dev/SocialNetwork/app/controller/DataController.php on line 713

@chilimatic its maybe a good time to rewrite the autoloader so it match psr-4 ?

http://www.php-fig.org/psr/psr-4/

**Comment by chilimatic** [comment]
yes, i can have a look at it in the evening :) unless you wanna do the honours :)

**Comment by andreas83** [comment]
i was trying to fix this bug on my own but failed miserably :baby_chick:

**Comment by andreas83** [comment]
thx
