### ISSUE TITLE
Fileupload

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#6]
Right now you can upload any document to /public/upload
We should somehow prevent uploading or executing php and other potentially dangerous filetypes

**Comment by andreas83** [comment]
@besn can we prevent executing php in /upload/ via server config ?

**Comment by besn** [comment]
i would opt to move /upload/ to a seperate subdomain that is configured to only serve static content. this would also prevent a (potentially) uploaded javascript from being executed on the main page because it wouldn't be the same origin.

**Comment by chilimatic** [comment]
:D i like it ! CORS ftw ! :)

**Comment by andreas83** [comment]
sounds good :+1:
