### ISSUE TITLE
Namespace Issues

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#61]
new psr-4 autoloading, or to be more specific, the namespace 
breaks the existing function from Backend. 

Would be cool if there is such thing like:

use SocialNetwork\app\model* 

Any idea to solve this issue @chilimatic ?

**Comment by chilimatic** [comment]
namespace transformer with the configured namespace injected -> can be done via trait or abstract model should be a 10 minute fix

**Comment by andreas83** [comment]
would be cool if you can support me here.. @chilimatic

**Comment by andreas83** [comment]
for reference 90d25c8889bbd7acce92339fa451666a1be34bb3

**Comment by andreas83** [comment]
The generic_list.php creates a relation to another object:
$relation = new $configuration->properties[$propertie]['relation'];

i tried to add the static method but does not work :( 
`ModelFactory::make((string)  $configuration->properties[$propertie]['relation']);`

Btw i found that other views also create objects,  and now have now clue about the namespace. 
What i learned from this namespace troubles, **we need unit tests**!

**Comment by chilimatic** [comment]
:D i agree, and don't forget separation of concerns :) 
-> the view should not create models :) it should take a list of models, 
if you are concerned about memory a generator, could help if you don't need hash maps

**Comment by andreas83** [comment]
so the next release will focus only on unit tests and unit tests and unit tests

>  the view should not create models :) it should take a list of models

100% agree  :+1: 

so next release will not only cover unit test, but also seperation of views and models, and unit tests :rabbit:

**Comment by andreas83** [comment]
any clue how i could fix the generic lists view in the mean time for presentation ?

**Comment by chilimatic** [comment]
should work now

**Comment by andreas83** [comment]
looks good, will close this issue for now!
thx for your good work !

**Comment by andreas83** [comment]
i have to reopen this issue, since the notification server have some trouble too

**Comment by chilimatic** [comment]
error msg ? :)

**Comment by andreas83** [comment]
PHP Fatal error:  Class 'WebSocketUser' not found in /home/lissi/dev/SocialNetwork/app/lib/WebSocketServer.php on line 156
