### ISSUE TITLE
Webm not replaced anymore 

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#62]
WebVideoTransformer is identical to VimeoTransformer.

**Comment by andreas83** [comment]
fixed

**Comment by chilimatic** [comment]
you can close with commits -> so the closing commit is referenced here

**Comment by andreas83** [comment]
i forgot to reference to ticket while commiting (49165881134d68cbc3a4bc59da0f575a6dabfafb and 110976d30f1a96c0d45ca677450a51cd3b2d37ce)
