### ISSUE TITLE
websocket server does not return latest notifications after some time (1-2 hours)

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#70]
i send getNotifications to sockets server, with an auth_cookie for authenticaton.
{"action":"getNotifications","auth_cookie":"107ef05dbf5619681a4c252f9d458d95"}

this works pretty well for some time, but after an hour or so, i always get an empty notification array back,
even the token is still valid (inside user table).
restarting the socket server fix this issue....

**Comment by chilimatic** [comment]
check the mysql timeout and if you "ping/reconnect" php is not ment to have long idle socket connections to the mysql server so the pdo could have closed the connection it would be a classic.

**Comment by andreas83** [comment]
@chilimatic thanks sounds very reasonable. 
may i reconnect every x minutes from mysql ?

**Comment by andreas83** [comment]
mhm this sounds good to me:
http://brady.lucidgene.com/articles/pdo-lost-mysql-connection-error

**Comment by chilimatic** [comment]
i made it conditional "if select 1 does not return a result reconnect" at least thats what i did in my framework pdoadapter :)

**Comment by andreas83** [comment]
mhm iam thinking about some sort of connection manager class ...  
i still wonder why there is no exception , error etc ...

**Comment by andreas83** [comment]
for reference b16840b282d682158b7bc0ac12c21c3ddd4a8579

lets see if it helps :+1:

**Comment by chilimatic** [comment]
since php was not built for anything else than the request response model, the stream connection error was not really necessary I guess. maybe they added an exception in php7 but i would have to test it. anyway it's a classic pdo error :) mysqli has the ping method :)

**Comment by andreas83** [comment]
mhm okay this "solution" wont fix the issue..  
i guess persistent connection won't neither?!

**Comment by chilimatic** [comment]
timeout is timeout you could reopen an close the connection everytime

**Comment by andreas83** [comment]
or making some sort of select statement every x minutes to keep the connection alive ?

**Comment by chilimatic** [comment]
still does not protect you from short network errors but you already decided what you wanna do so just do it :)

**Comment by andreas83** [comment]
sorry for switching to german but i guess its easier for the moment. 

> but you already decided what you wanna do so just do it 

eigentlich hab ich noch gar nichts entschieden, ich bin immernoch auf der Suche nach einer Lösung. 

Die änderung: b16840b282d682158b7bc0ac12c21c3ddd4a8579 war nur ein versucht und hat leider nicht funktioniert, hab das ganze gerade nochmal direkt am server modifiziert um zu schauen ob es jetzt vieleicht geht...  

leider kann ich den fehler nicht so einfach nachstellen, (ausser ich setzt die timeout nach unten).
das mit dem alle x sekunden den server anfragen war eine ernst gemeinte frage...

**Comment by chilimatic** [comment]
du kannst in der mysql konsole die connection mit kill terminieren soweit ich weiß.
und du hast das mit den x selects vorher schon erwähnt, also denk ich das es dein Lösung ist und du dich schon dafür entschieden hast bzw du bevorzugst, sonst würdest du es nicht noch einmal erwähnen. 

Das ganze problem lässt sich auf verschiedenste arten lösen. ob du jetzt versuchst die verbindung durch "durchgehende queries offen zu halten" oder du sagst "ich connecte jedes mal neu" oder du sagst "alle 10 minuten schließe ich die verbindung und mache eine neue auf". ist geschmack die "ich connecte jedes mal neu ist warscheinlich die mit der geringsten ausfall möglichkeit hat aber den durchgehenden overhead der initialisierung der verbindung. Die anderen connection offen halten hat das problem, dass wenn aufgrund anderer umstände die verbindung nicht geschlossen wurde du immer noch den gleichen error haben wirst. und die ich verbinde alle 10 minuten neu kann im worstcase 10 minuten connection loss bedeuten.

die bereits implementierte gehört warscheinlich nur ein bisschen nachgebessert allerdings habe ich ja nur aufgrund meiner erfahrungswerte geraten.

**Comment by andreas83** [comment]
neben ich connecte jedes mal neu und ich connecte alle x minuten wäre mir eigentlich am liebsten, 
dass er einen reconnect versuch macht, wenn er "mysql has gone away"  als exception bekommt. 
wenn dieser versuch erfolgreich ist, kann er den "nur ein reconnect versuch" flag wieder resetten bis zum nächsten versuch :)

nachdem ich die dbhandler, interfaces und traits von dir nicht 100% verstehe würde ich dich eigentlich auch bitten das du mich hier etwas unterstützt :rose:

**Comment by chilimatic** [comment]
fauler sack! :P ich schau's mir morgen an bin heut noch fertig von der gestrigen geburtstagsfeier :)

**Comment by andreas83** [comment]
Ein paar dinge die ich jetzt herausgefunden habe. 
1.) Man kann es mit show processlist und kill nachstellen (danke)
2.) Exception wirft der WebSocketServer !?
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Was mich etwas verwundert, bin eigentlich davon ausgegangen das die Exception irgendwo im dbhandler geworfen wird und ich dort einfach ein reconnect machen kann....  

Wäre über deine Hilfe immernoch sehr dankbar!

**Comment by chilimatic** [comment]
hmm cool. das mim error war mir klar nachdem ich bei dir nur eine initalisierungs abstraktion gebaut habe und nicht wirklich ein volles adapter konzept mit interface implementiert habe. Oder direkter gesagt ... du verwendest immer noch PDO direkt. Die exception passiert natürlich dort wo die objekt referenz aufgerufen wird -> da es keine wrapped "query" methode gibt. 

ich hab heut leider bis um 21:30 durch gearbeitet  und bin morgen auf einem kunden termin, dann die nächsten 2 tage in deutschland bei einem kunde und dann am freitag ebenfalls wieder bei einem kunden gespräch . vllt hab ich zeit es mir im zug anzuschaun, ich denke für dich wäre es das einfachste das problem lokalisiert -> im websocket zu behandeln. 

Eine andere "einfache" Lösung wäre die PDO klasse zu extenden und die fälle zu catchen und einen reconnect auszuführen. hat natürlich einen gewissen performance verlust aber stabilität ist hier wohl wichtiger :)

**Comment by andreas83** [comment]
ich lasse das tickets zu sicherheit mal 24h offen, sollte aber mit 6b195945cde254e9921f4350eaf133475254de6b erledigt sein. 

Ich verwende jetzt die Lösung von https://gist.github.com/extraordinaire/4135119
Vieleicht gibt es aber noch eine bessere Lösung als ständig ein show status zu callen.

**Comment by andreas83** [comment]
Die Lösung funktioniert, womit das Ticket auch geschlossen werden kann. 
Werde noch ein follow up ticket eröffnen, wo es darum geht, den ConnectionManager zu optimieren.
Glaube die Lösung ist nicht die effizienteste.
