### ISSUE TITLE
Put user links into own namespace

### ISSUE THREAD

**Issue by neuron303** [andreas83/SocialNetwork#76]
Personal pages are located at
`http://www.dasmerkendienie.com/<username>`
Proposal:
Put them into namespace "user" or "nick"
e.g.
`http://www.dasmerkendienie.com/nick/<username>`

Reason:
User names can collide with existing links
see http://www.dasmerkendienie.com/permalink/19261
and click on the username ;)

**Comment by andreas83** [comment]
i prefer to reserve namespaces like /hash or /permaling ...

**Comment by chilimatic** [comment]
@andreas83 is this sarcastic ? because he just suggested to reserve 1 more namespace for all users which at least as I understand makes a lot of sense. And it has nothing to do with your namespaces . Or do I miss something ?

**Comment by andreas83** [comment]
> i prefer to reserve namespaces like /hash or /permaling ...

was ich mit der aussage meinte, mir wäre es lieber bei der registrierung usernames
mit /hash/blub am anfang zu verbieten, als alle links zum userprofile ändern. 
A cool URI is one which does not change - https://www.w3.org/Provider/Style/URI.html

**Comment by chilimatic** [comment]
hmmm verstehe, also eine designfrage. Ich hab mir das jetzt durchgelesen und versteh schon was er meint allerdings frag ich mich wieviel user dmdn hat und wieviele ihre profile regelmässig aufrufen und warum man nicht einfach einen redirekt macht ? Aber ja das ist jetzt geschmack :D und es ist dein Baby :)

**Comment by neuron303** [comment]
@andreas83 you are right that these are actually seperate problems and that usernames that contain path elements shouldnt be accepted.
i just noticed that the namespaces are "inconsistent" and will open a seperate issue.

the design decision to put users into root is valid but shouldnt be made lightheartedly since there is only one :) since the site is still in its infancy this change can be made imo. cool uris dont change and thats why i made the proposal in the first place. the root namespace is prone to conflict and might make a change necessary :)
