### ISSUE TITLE
Do not use uniqid() to reset password

### ISSUE THREAD

**Issue by neuron303** [andreas83/SocialNetwork#78]
http://php.net/manual/en/function.uniqid.php

As stated in the manual this function should not be used for security purposes as it is not unpredictable

**Comment by andreas83** [comment]
i my opinion this is a very unlikely case, but anyway lets try to fix it. 
my approach would be something like this:

 `md5(uniqid($your_user_login, true))`

any other recommendations ?

**Comment by chilimatic** [comment]
`password_hash(MD5(uniqid(mcrypt_create_iv(22, MCRYPT_DEV_URANDOM), true)), PASSWORD_BCRYPT, ['cost' => 8]);`

but then you could not validate the password via the database anymore. 

so how about 

`MD5(uniqid(mcrypt_create_iv(22, MCRYPT_DEV_URANDOM), true));` 

still weak because of the low timecomplexity calculating MD5s (dictionary attack) but at least a little bit more random

**Comment by andreas83** [comment]
> but then you could not validate the password via the database anymore.

???  
its about the password reset hash send to a user, there is no password validation involved...

**Comment by chilimatic** [comment]
ahh i thought you set a temporary password .... :D if that's the issue ... who cares ? :D there is a possiblity of collisions but it's marginal and your plattform has such a low number of users atm :)

**Comment by andreas83** [comment]
mhm sorry i was wrong, i send a temp password while someone is clicking on the confirmation link.
but jepp is still a very unlikely security issue

**Comment by andreas83** [comment]
so the real question is, is uniqID good enough for temp passwords?
my answere is, yes it is!

of cause i could create md5 hashes from some more or less random garbage, but of cause there is the possibility of collision too. 

keep in mind, this is a very unlikely case, where an attacker can predict the password, 
and is able to convince you to click on the reset link (without this action, the temp pw is not valid). 

another workaround could be to force the account holder to create a new
password after clicking the reset link in email. this would solve the whole issue.

**Comment by chilimatic** [comment]
I would force him. that's a short windows and if you just add the mcrypt_create_iv(22, MCRYPT_DEV_URANDOM) as prefix in the uniquid it's very unlikely but still you could predict it :D but if someone wanna posts cat pictures so badly .... let him have it :D

**Comment by andreas83** [comment]
After a short discussion with @neuron303 i decided to replace my api_key generation 
with a stronger method.
