### ISSUE TITLE
create build script in phing

### ISSUE THREAD

**Issue by chilimatic** [andreas83/SocialNetwork#8]
Create a build script in phing that 
- check if composer exists
- check if npm exists
- triggers composer and npm update / install
- triggers bower
- triggers phpunit 
- triggers a database migration script state

**Comment by andreas83** [comment]
still like the idea of a build script, thats the reason why i created my first composer.json file... 
would love to chat about the pro/con of the different approaches, so just drop me a line if you have some time

**Comment by andreas83** [comment]
Our "working" setup right now is:

**bower for frontend libs**
for bootstrap, jquery, react, fontawesome, highlightjs 

**npm for development libs**
bower, gulp, babel etc 

**gulp for build automation**

sass, react, compress, icons are working tasks

Next step should be #57  and the phing script which should put all together.

**Comment by chilimatic** [comment]
my phing repos already supports gulp, bower, selenium, composer, git, curl, behat, grunt, phinx...
so i guess this would be around 20 minutes to compose a phing build.xml 

if the frontend related tasks are within the gulp configuration this should be easy going. 

the native phing phpunit tasks needs phpunit globally installed (something i don't like because I have many projects with different versions) but I can build you a custom one if the structure is right -> composer bin directory is in /bin and such details.

**Comment by chilimatic** [comment]
#66
