### ISSUE TITLE
performance issue with db connection manager

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#81]
i just created a new db connection for every record :+1: 

bugfix: fbc57bb55e35107ca3c628bc9e8a975106687c41

the troube is this one line:
$stmt->fetchALL(\PDO::FETCH_CLASS, $this->className);

i noticed that PDOs fetchALL creates a new object for every row from the query result, 
the problem is $this->className constructor als  creates a new db connection for every time its called. 

 i feel so special  :sob:

**Comment by chilimatic** [comment]
just use 

```
array(
    PDO::ATTR_PERSISTENT => true
) 
```

you don't use transactions

**Comment by andreas83** [comment]
me meine letzte änderung fbc57bb55e35107ca3c628bc9e8a975106687c41 hat dazu geführt,
das #70 wieder aktuell wird

**Comment by chilimatic** [comment]
hmmm verstehe, naja meine Lösungsvorschläge dafür stehen eh dort, vllt fällt ja @besn @neuron303 was dazu ein :).

**Comment by andreas83** [comment]
find momentan deine lösung mit dem pdo extenden noch am besten, weil man so 
explizit den fehlerfall behandeln könnte.
in wahrheit wüsste ich auch keine alternativen mehr, ausser  persistent connection ...

**Comment by chilimatic** [comment]
hmm ja. ist natürlich eine Möglichkeit, alles hat wie immer pro und cons :)

**Comment by andreas83** [comment]
@chilimatic kann es sein das auch persisten connections ein timeout haben ?

**Comment by chilimatic** [comment]
jipp kann gut sein, das timeout kommt von der DB wenn eine connection zu lange idled.
die persistent connections sind ja nur, dass es eine reduzierte anzahl von Verbindungen innerhalb eines aktiven threads aufgebaut werden. 

Wenn der Thread aber lange läuft und kein stream über den client auf den server passiert sollte das verhalten gleich sein. An das hab ich voll nicht gedacht sorry :/

**Comment by andreas83** [comment]
witzigerweise hab ich das issue auf dem neuen server nicht mehr... scheinbar gab es unterschiede in der server konfiguration die dazu geführt hat, das soviele connections aufgemacht wurden ....
