### ISSUE TITLE
How should I do the permission part when I run this on Windows10?

### ISSUE THREAD

**Issue by rolltale** [andreas83/SocialNetwork#85]
Fatal error: Call to undefined function _() in C:\AppServ\www\SocialNetwork\app\template\menu.php on line 33

**Comment by andreas83** [comment]
Please make sure PHP Gettext is installed.

**Comment by andreas83** [comment]
Just make sure the upload folder is writeable by webserver. 
Also i am not sure about the socket server, never tested it on windows.
