### ISSUE TITLE
http2 preload aka server push

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#86]
not sure if its Social Network or Chrome itself but when i add following header to nginx, reloading of our  demo site breaks chrome. 

`add_header link '</public/css/style.min.css>; rel=preload';`
`add_header link '</public/js/app.js>; rel=preload';`

**Comment by andreas83** [comment]
@besn @chilimatic  please can you confirm this bug?

**Comment by chilimatic** [comment]
@andreas83 I'll put in my calendar and try to confirm it till Tuesday next week.

**Comment by andreas83** [comment]
can reproduce this issue on another computer. 
chrome Version 51.0.2704.84 (64-bit)
ubuntu xenial

steps to reproduce: 
go to demo site: 
http://www.dasmerkendienie.com/ 
hit reload 
Chrome drops a oh no error message!?

very strange behavior

**Comment by andreas83** [comment]
i just removed the preload header and now everything works fine...
```
add_header link '</public/css/style.min.css>; rel=preload';
add_header link '</public/js/app.js>; rel=preload';
```
