### ISSUE TITLE
[Composer\Downloader\TransportException] Content-Length mismatch

### ISSUE THREAD

**Issue by rolltale** [andreas83/SocialNetwork#87]
**At the composer install step**

- Loading composer repositories with package information
- Updating dependencies (including require-dev)
- 
- 
-   [Composer\Downloader\TransportException]
-   Content-Length mismatch
- 
- 
- install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
- 

# Have no idea to figure it out

**Comment by chilimatic** [comment]
have you tried `composer selfupdate` as well as `composer clear` before running the installation ? 

Please provide general environment information like 
the operation system and composer version so we are able to help/test accordingly.

**Comment by rolltale** [comment]
I tried `composer selupdate` and `composer clear` just now, and there are some new issues appeared.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit 4.8 -> satisfiable by phpunit/phpunit[4.8.0].
    - phpunit/phpunit 4.8.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 2
    - league/oauth2-client 1.4.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - league/oauth2-client 1.4.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - league/oauth2-client 1.4.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - league/oauth2-client 1.3.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for league/oauth2-client ^1.3 -> satisfiable by league/oauth2-client[1.3.0, 1.4.0, 1.4.1, 1.4.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
**@chilimatic Thanks for answering
OS : Ubuntu(Linux)
PHP : 7.0.15
composer : 1.4.1**

**Comment by chilimatic** [comment]
ahhh :D 

`sudo apt-get install php-curl php-xml`
and retry :) let me know if it worked out :) I use arch so I'm not quite sure if I used the correct curl packages 

`sudo apt-cache search php | grep curl` should give yo the right result

**Comment by chilimatic** [comment]
and don't forget to restart your fpm or if you used apache mod your apache, if it's not happening automatically :)

**Comment by rolltale** [comment]
@chilimatic Thank you very much! It worked `sudo apt-get install php-curl php-xml`
This issue borthered me a week.
Thanks again~

**Comment by chilimatic** [comment]
you're welcome ! :)

**Comment by andreas83** [comment]
@chilimatic thx!
