### ISSUE TITLE
Fatal error: Uncaught Error: Class 'AltoRouter'

### ISSUE THREAD

**Issue by visheshCuriousDev** [andreas83/SocialNetwork#88]
Fatal error: Uncaught Error: Class 'AltoRouter' not found in C:\xampp\htdocs\SocialNetwork\routing.php:5 Stack trace: #0 C:\xampp\htdocs\SocialNetwork\init.php(6): include_once() #1 C:\xampp\htdocs\SocialNetwork\index.php(9): require_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\SocialNetwork\routing.php on line 5

Why this error occurs where is the AltoRouter declared ??

**Comment by andreas83** [comment]
just in case someone else read this ticket, the solution is simply run composer update
