### ISSUE TITLE
create database migration manager

### ISSUE THREAD

**Issue by chilimatic** [andreas83/SocialNetwork#9]
We need a manager to 
- save the current state of the database
- imports the migration scripts

this is so we don't get inconsistent with the environment differences in the database.
and we can build a live system from scratch without legacy dummy data.

**Comment by andreas83** [comment]
Good idea, we could have a update script which checks the db version vs git db version and runs the sql upgrade files.

**Comment by chilimatic** [comment]
I like the idea :D maybe we should create a flowchart to see what makes sense or we just prototype :D

**Comment by andreas83** [comment]
not sure how a flowchart will help, but would love to see some progress here :+1:

**Comment by chilimatic** [comment]
give me reasons not an opinion :) the "because" is important to me. 

because I think coding slow, with plans, allows you to see future problems and you get a nice overview of what has to be done.

you could share the idea and discuss about it before you implement it. 
We all forget some Things, we all have our opinions how the code should look like, so we should share the idea in whatever **not code based way** as possible.

we need to implement a process where we can share ideas before we code them! So that we can focus on the functionality and purpose without talking about code. 

Put simple if you build any technical device you need blueprints, I already seen multiple such managers so i don't feel the need to prototype one. In fact I know exactly what I wanna code, but there is a chance I forgot something.

as a gentle reminder to your "get it done attitude" vs my "DRY/ACID/SOLID" approach which always is much more tedious than yours.

I just want to find a level ob abstraction where we can communicate the ideas not how we write it or how we think the architecture should look like. If you know something better than a flow diagram tell me something, I know it moves "productive" time into the planning time but if you do it right you have a well tested and isolated piece of software.

That's my "because" so now please give me yours,

**Comment by andreas83** [comment]
i would love to talk about your "DRY/ACID/SOLID" and my "get it done attitude" attitude.
imho both are highly valuable and equally important, also i think we can just benefit from each other too.
but why not discuss this on another channel, since this ticket is about the update/migrations of database changes.

my approach in general would be: 
1.) the best argument should win
2.) do whatever it takes to get it done

if a flowchart - in example - helps go for it!
if the flowchart did not worke out, doesn't matter as long as we learned something from it.

**Comment by andreas83** [comment]
back to topic again, i like to evaluate https://phinx.org/

**Comment by andreas83** [comment]
Now we will use the migration manager from laravel see dev branch

**Comment by chilimatic** [comment]
out of curiosity :) ... y ? y laravel ? :) I've read the spec they look good actually. But still that's what I've been arguing in the first place ;D ... unless you actually compare them (make a blog entry out of it or whatever.) you actually are going for an opinionated decision not a factual :)
