### ISSUE TITLE
some files missing

### ISSUE THREAD

**Issue by ghost** [andreas83/SocialNetwork#90]
Warning: include_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\SocialNetwork-master\init.php on line 5

Warning: include_once(): Failed opening 'vendor/autoload.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\SocialNetwork-master\init.php on line 5

Fatal error: Class 'AltoRouter' not found in C:\xampp\htdocs\SocialNetwork-master\routing.php on line 5

**Comment by andreas83** [comment]
Hi Davis, 
you need to run composer first, please have a look here:
https://github.com/andreas83/SocialNetwork#install-dependencies

**Comment by ghost** [comment]
thank you bro... honestly your works are inspiring also with your Codes they are amazing... Am still a novice when it comes to php mysqli if you have tutorials for me that would be great. Here's is my Email: davismail200@gmail.com.

am actually designing a social network and am having problem on file upload using session "based on logged in user" is a system where you can store your photos, documents, music & videos... While you can also share, like and send private messages... i will be glad if you can help me out..

And thank you ("Andreas")
