### ISSUE TITLE
Sorry Am writing you this because i don't know how to contact you

### ISSUE THREAD

**Issue by ghost** [andreas83/SocialNetwork#91]
thank you bro... honestly your works are inspiring also with your Codes they are amazing... Am still a novice when it comes to php mysqli if you have tutorials for me that would be great. Here's is my Email: davismail200@gmail.com.

am actually designing a social network and am having problem on file upload using session "based on logged in user" is a system where you can store your photos, documents, music & videos... While you can also share, like and send private messages... i will be glad if you can help me out..

And thank you ("Andreas")

**Comment by andreas83** [comment]
you can contact me via andreas@moving-bytes.at
