### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by thakurabhishek795** [andreas83/SocialNetwork#92]
how to run this on my localhost, var/www/html   is my localhost directory 
I'm using Apache server, os-  ubuntu 

https://imgur.com/a/UgWeX      --- view of this project when I'm running this in browser

**Comment by chilimatic** [comment]
hey, 

did you set 

```
address="http://www.yourdomain.com"
dir="/var/www/vhost";
```
in your configuration ? this looks like the address / path is missing for the CSS files.

**Comment by thakurabhishek795** [comment]
; URL 
address="http://localhost/SocialNetwork"
; Path to URL
dir="/var/www/html/"

; Upload path & address
upload_path="/public/upload/"
upload_address="http://localhost/public/upload/"


https://imgur.com/a/SgR5U       image of my file system

is this ncessary to put file inside the vhost?

**Comment by chilimatic** [comment]
I don't thinks so the .htaccess should take care of the rewrites.

I would check the apache logs next to see what the css request answers with. maybe you forgot to set the correct read permissions for those folders.

**Comment by thakurabhishek795** [comment]
I have given 777  permission to all var/www file

**Comment by thakurabhishek795** [comment]
is there any way to ssh or remote desktop to my computer so you can check this?

**Comment by chilimatic** [comment]
teamviewer would be 1 possibillity

http://www.p2p-network.net/webchat.php 

channel social-network

**Comment by thakurabhishek795** [comment]
what I have to fill in Channel  and  key option

**Comment by chilimatic** [comment]
http://www.p2p-network.net/webchat.php -> channel: social-network :) nickname just pick one :) and we talk there

**Comment by chilimatic** [comment]
fixed it via remote session -> it was a local apache configuration issue :)

**Comment by thakurabhishek795** [comment]
Thank you for solving my problem... but what is the major problem .... file locations or something else?

**Comment by chilimatic** [comment]
@thakurabhishek795 the document root was not set in you apache config :) and the configuration was messed up because you were compensating for it :)

**Comment by andreas83** [comment]
thx @chilimatic
