### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#94]
Feature Request -> Comment improvement:

- [ ] Edit & Delete (mandatory) 
- [ ] Links clickable (mandatory)
- [ ] Reply function (mandatory)
4. Links witch preview (nice to have) 
5. Like comments (nice to have) 

Open Questions:

Anything else which is mandatory for our new comment section? 
How many levels of reply should be possible ? 

Would love to get some feedback, in special from @besn @neuron303 and @chilimatic  :heart:

**Comment by besn** [comment]
@andreas83 the requested features are looking good. maybe embedding images from the local or certain whitelisted domains so you can comment with a gif would be nice :)

regarding the depth for comments i would suggest making it (virtually) infinite (with a "show more" link at a certain depth) but configurable so the administrator can limit it if they want to.
