### ISSUE TITLE
/public/stream Not Found

### ISSUE THREAD

**Issue by FeverKing** [andreas83/SocialNetwork#98]
Hi,
Sorry to trouble you, but it seems that /public/stream is missing during the installation. Please tell me how to fix it.
Thx

**Comment by FeverKing** [comment]
Also my css files seems not working..

**Comment by andreas83** [comment]
Do you use apache and have mod rewrite enabled ?? 
its needed for the url rewrite stuff, there is also a example for nginx in the documentation

**Comment by FeverKing** [comment]
Oh Ic, thx for that.
I just read about apache and didn't see the nginx conf below
Thank u anyway :)
